import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {
	MatPaginatorModule,
	MatButtonModule,
	MatCardModule,
	MatCheckboxModule,
	MatRadioModule,
	MatDatepickerModule,
	MatDividerModule,
	MatGridListModule,
	MatIconModule,
	MatInputModule,
	MatListModule,
	MatMenuModule,
	MatNativeDateModule,
	MatSelectModule,
	MatSidenavModule,
	MatTableModule,
	MatSortModule,
	MatTabsModule,
	MatToolbarModule,
	MatDialogModule,
	MatSlideToggleModule,
	MatAutocompleteModule,
	MatFormFieldModule,
	MatChipsModule
} from '@angular/material';

import {BrowserModule} from '@angular/platform-browser';

@NgModule({
	imports: [
		CommonModule,
		MatDialogModule,
		MatPaginatorModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatTabsModule,
		MatTableModule,
		MatListModule,
		MatToolbarModule,
		MatSidenavModule,
		BrowserModule,
		MatMenuModule,
		MatSelectModule,
		MatCardModule,
		MatSortModule,
		MatDividerModule,
		MatButtonModule,
		MatCheckboxModule,
		MatRadioModule,
		MatGridListModule,
		MatInputModule,
		MatIconModule,
		BrowserAnimationsModule,
		MatSlideToggleModule,
		MatAutocompleteModule,
		MatFormFieldModule,
		MatChipsModule,
	],
	exports: [
		MatDialogModule,
		MatPaginatorModule,
		MatDatepickerModule,
		MatTabsModule,
		MatTableModule,
		MatListModule,
		MatMenuModule,
		MatSelectModule,
		MatCardModule,
		MatSortModule,
		MatDividerModule,
		MatButtonModule,
		MatToolbarModule,
		MatSidenavModule,
		MatCheckboxModule,
		MatRadioModule,
		MatGridListModule,
		MatInputModule,
		MatIconModule,
		MatSlideToggleModule,
		MatAutocompleteModule,
		MatFormFieldModule,
		MatChipsModule,
	],
	providers: [MatNativeDateModule]
})
export class MaterialModule {
}
